name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # каждый день
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/generate-readme-md-snake@v1
        with:
          github_user_name: y4sn0kl0un
          output: dist/snake.svg
          color_snake: "#3B82F6"
          color_dots: "#E5E7EB,#93C5FD,#60A5FA,#3B82F6,#1E40AF"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
